

POST http://localhost:8000/signup
Content-Type: application/json

{
    "firstname":"kennedy", 
    "lastname":"marvellous", 
    "email":"kennedymarvellous001@gmail.com", 
    "gender":"male", 
    "pass":"word1234"
}


###
GET http://localhost:8000/login
content-type: application/json

{
    "email":"kennedymarvellous001@gmail.com",
    "pass":"word1234"
}

###
GET http://localhost:/getuser/id